### ISSUE TITLE
[Question] What license is this project using?

### ISSUE THREAD

**Issue by thshdw** [astuteo/slickmap#1]
Hello, 
I'm curious to know what license this project is using; can I use this in a corporate environment without attribution?

**Comment by mg1075** [comment]
@thshdw - I don't see a license, but the website example has this notice:

- https://www.astuteo.com/slickmap/

> SlickMap CSS was created by Matt Everson of Astuteo – that’s me – and it’s entirely free for you to download and use, modify for your own applications, or otherwise make millions off of. That said, my office is directly above a pub, so should you find yourself so overwhelmed with gratitude that you can’t help but buy me a cold beer, there’s no doubt the gesture will be accepted; prefaced with a brief but heartfelt toast to your own personal and professional success. Either way, enjoy.

**Comment by astuteo** [comment]
An "unlicense" has been added to the repo, reinforcing the statement above.
